In [125]:
print("This is Kolhapur")

This is Kolhapur


## Variable

In [2]:
name ="VaibhaV"

In [3]:
print(name)

VaibhaV


In [4]:
name = "Sheetal"

In [5]:
print(name)

Sheetal


## Data type
- int
- float
- Boolean
- String

In [6]:
num1= 1 
print(type(num1))
num2= 2.303 
print(type(num2))
num3= True 
print(type(num3))
num4= "VaibhaV" 
print(type(num4))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


## Operators


## Arithmatic Operator +, -, *, /

In [7]:

num1, num2 =36, 7

In [8]:
num1 + num2

43

In [9]:
num1 - num2

29

In [10]:
num1 * num2

252

In [11]:
num1 / num2

5.142857142857143

In [12]:
num1 // num2

5

## Relational Operator <, >, ==, !=


In [13]:
num1 > num2

True

In [14]:
num1 < num2

False

In [15]:
num1 == num2

False

In [16]:
num1 != num2

True

## Logical Operator & |


In [17]:
log1 = True
log2 = False

In [18]:
log1 & log2

False

In [19]:
log1 & log1

True

In [20]:
log1 | log1

True

## Python Tokens
Smallest meaning full componet in program
- Keywords : Special reversed words like For If Yield
- Identifiers: Names used for variables, functions or objects
- Literals : Costants in python
    - num = "Test" : here "num" is Identifier and "Test" is literal
- Operators

## String:


In [21]:
str1 = "I love Pizza"
str1.find("Piz")

7

In [22]:
fruits ="Mango, Banana, Apple"
fruits.split(", ")

['Mango', 'Banana', 'Apple']

## List

In [23]:
l1 = [1, "a", 2, True]

In [24]:
l1[0]=100
l1


[100, 'a', 2, True]

In [25]:
l1.append("VaibhaV")
l1

[100, 'a', 2, True, 'VaibhaV']

In [26]:
l1.pop()

'VaibhaV'

In [27]:
l1

[100, 'a', 2, True]

In [28]:
l1.reverse()
l1

[True, 2, 'a', 100]

In [29]:
l1.insert(1, "Test")
l1

[True, 'Test', 2, 'a', 100]

In [30]:
l1.sort()
l1

TypeError: '<' not supported between instances of 'str' and 'bool'

In [31]:
l2 = ['Mango', 'Banana', 'Apple']
l2.sort()
l2


['Apple', 'Banana', 'Mango']

In [32]:
l1 = ["a", "b", "c"]
l2 = [1, 2, 3]
l1+ l2

['a', 'b', 'c', 1, 2, 3]

In [33]:
l1 = [1, "b", True]
l1 * 3

[1, 'b', True, 1, 'b', True, 1, 'b', True]

## Tuple
- Tuple are ordered collection of elements enclosed within ()
- Tuples are immutable, once created we can not update or change values of tuple

In [34]:
tup1 = (1, "b", True)
tup1

(1, 'b', True)

In [35]:
type(tup1)

tuple

In [36]:
tup2 = tup1 *3 
tup2

(1, 'b', True, 1, 'b', True, 1, 'b', True)

In [37]:
tup2[1:6]

('b', True, 1, 'b', True)

In [38]:
tup2[::2]

(1, True, 'b', 1, True)

In [39]:
tup2[2]="Test"

TypeError: 'tuple' object does not support item assignment

In [40]:
tup1 = ("a", "b", "c")
tup2 = (1, 2, 3)
tup1 + tup2

('a', 'b', 'c', 1, 2, 3)

## Dictionary
- Dictionary is an unordered collection of key-value pairs enclosed with {}
- Dictionary is mutable

In [41]:
fruit = {"Mango": 10, 'Banana': 20, 'Apple':30}

In [42]:
fruit.keys()

dict_keys(['Mango', 'Banana', 'Apple'])

In [43]:
fruit.values()

dict_values([10, 20, 30])

In [44]:
fruit["Guava"]=40
fruit

{'Mango': 10, 'Banana': 20, 'Apple': 30, 'Guava': 40}

In [45]:
fruit

{'Mango': 10, 'Banana': 20, 'Apple': 30, 'Guava': 40}

In [46]:
f1 = {'Mango': 10, 'Banana': 20}
f2 = {'Apple': 30, 'Guava': 40}

In [47]:
f1.update(f2)
f1

{'Mango': 10, 'Banana': 20, 'Apple': 30, 'Guava': 40}

In [48]:
f1.pop("Guava")


40

In [49]:
f1

{'Mango': 10, 'Banana': 20, 'Apple': 30}

## Set
- Set ia a unordered and unindexed collection of elements enclosed with {}
- Duplicates are not allowed in Set


In [50]:
# Try duplicates with set
s1 = {"c", "a", "b", 1, 2, 3, "a", "b", 1, 2}
s1

{1, 2, 3, 'a', 'b', 'c'}

In [51]:
s1.add("Test")
s1

{1, 2, 3, 'Test', 'a', 'b', 'c'}

In [52]:
s1.remove("b")
s1

{1, 2, 3, 'Test', 'a', 'c'}

In [53]:
s1 = {'Mango', 'Banana', 'Apple', 1, 2, 'a'}
s2 = {'a', 'b', 'c', 1, 2}
s1.union(s2)

{1, 2, 'Apple', 'Banana', 'Mango', 'a', 'b', 'c'}

In [54]:
s1

{1, 2, 'Apple', 'Banana', 'Mango', 'a'}

In [55]:
s2

{1, 2, 'a', 'b', 'c'}

In [56]:
s1.intersection(s2)

{1, 2, 'a'}

## Decision making


In [57]:
a, b= 10, 20

In [58]:
if a>b:
    print("A is greater than B")
else:
    print("B is greater than A")

B is greater than A


In [59]:
result= "A is greater than B" if a>b else "B is greater than A"
result

'B is greater than A'

In [60]:
tup= ("a", "b", "c")

In [61]:
if "z" in tup:
    print("z is in tup")
else:
    print("z is not in tup")

z is not in tup


## Looping Statement
To repeat task multiple times

In [62]:
fruit = ['Mango', 'Banana', 'Apple']
for frt in fruit:
    print(frt)

Mango
Banana
Apple


In [63]:
i= 1
while i<=10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


## Object Oriented Programming
- Class: user defined data type
    - Attributes
    - Methods
- Objects : Specific instance of a class

In [64]:
class Phone:
    def make_call(self):
        print("Making phone call")
    def play_game(self):
        print("Playing game")
    def set_color(self, color):
        self.color = color
    def set_cost(self, cost):
        self.cost = cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost

In [65]:
p1 = Phone()

In [66]:
p1.make_call()

Making phone call


In [67]:
p1.play_game()

Playing game


In [68]:
p1.set_color("Red")

In [69]:
p1.set_cost(1000)

In [70]:
p1.show_color()

'Red'

In [71]:
p1.show_cost()

1000

### Constructor

In [72]:
class Phone:
    def __init__(self, color, cost):
        self.color = color
        self.cost = cost
    def make_call(self):
        print("Making phone call")
    def play_game(self):
        print("Playing game")

In [73]:
p1 = Phone("Red", 2000)

In [74]:
p1.color

'Red'

## Inheritance
With inheritance one class can derive the properties of another class

In [75]:
class Vehicle:
    def __init__(self, mileage, cost):
        self.mileage = mileage
        self.cost = cost
        
    def vehicle_details(self):
        print(f"Vehicle has {self.mileage} mileage and it cost ${self.cost}")

In [76]:
v1 = Vehicle(27, 15000)
v1.vehicle_details()

Vehicle has 27 mileage and it cost $15000


In [77]:
class Car(Vehicle):
    def show_car(self):
        print("I am Car")
        

In [78]:
c1 = Car(200, 15000)

In [79]:
c1.show_car()

I am Car


In [80]:
c1.vehicle_details()

Vehicle has 200 mileage and it cost $15000


In [81]:
class Car(Vehicle):
    def __init__(self, mileage, cost, hp ):
        super().__init__(mileage, cost)
        self.hp = hp
    def show_car(self):
        print(f"I am car with mileage: {self.mileage}, cost: {self.cost}, power: {self.hp} ")

In [82]:
c1= Car(100, 15000, 2000)

In [83]:
c1.show_car()

I am car with mileage: 100, cost: 15000, power: 2000 


In [84]:
c1.vehicle_details()

Vehicle has 100 mileage and it cost $15000


## Multiple Inheretance
Child inherite more than one parent class

In [85]:
2
    

2

In [86]:
c1 = Child()
c1.assign_string_1("One")
c1.assign_string_2("Two")
c1.assign_string_3("Three")

NameError: name 'Child' is not defined

In [87]:
print(c1.show_string_1())
print(c1.show_string_2())
print(c1.show_string_3())

AttributeError: 'Car' object has no attribute 'show_string_1'

## Multi Level Inheritance
-We have Parent, Child, grand-child

In [88]:
class Parent1:
    def assign_name(self, name):
        self.name = name
    def show_name(self):
        return self.name
    
class Child(Parent1):
    def assign_age(self, age):
        self.age = age
    def show_age(self):
        return self.age
    
class GrandChild(Child):
    def assign_gender(self, gender):
        self.gender = gender
    def show_gender(self):
        return self.gender
    


In [89]:
gc = GrandChild()

In [90]:
gc.assign_name("Test")

In [91]:
gc.assign_age(21)

In [92]:
gc.assign_gender("Male")

In [93]:
print(f"{gc.show_name()} is a {gc.show_gender()} aged {gc.show_age()}")

Test is a Male aged 21


## File Handling
- Open mode : Open text file for reading, writing and doing some other stuff
- Read mode : To read the text which is already stored in your text file
- Write mode : To write your text in .txt file


In [94]:
file = open('test.txt', 'w')

try:
    file.write('Chai aur code line 1')
finally:
    file.close()

In [95]:
file = open('test.txt', 'a')

try:
    file.write('\nChai aur code line 2')
finally:
    file.close()

In [96]:
file = open('test.txt', 'r')
data_read = file.read()
total_count = len(data_read)
print(total_count)

41


## Readline functions


In [97]:
f = open('test.txt', 'w')
f.write("I am learning file handling")
f.write("\n Topic is file handling, read and write")

40

In [98]:
f = open('test.txt', 'r')

In [99]:
print(f.readline())

I am learning file handling



In [100]:
print(f.readline())

 Topic is file handling, read and write


In [101]:
print(f.readline())

## Try Except

In [102]:
a =input("Enter the number 1 : ")
b =input("Enter the number 2 : ")

try:
    c= int(a) + b
    print(c)
except Exception as e:
    print(e)
    

Enter the number 1 : 1
Enter the number 2 : 2
unsupported operand type(s) for +: 'int' and 'str'


In [103]:
try:
    c= int(a) + b
    print(c)
except:
    print("Error in try block")

Error in try block


## Try with else clause
Else clause is used with the try clause when you want to execute the set of instructions in the absence of exceptions in your code

In [104]:
a =input("Enter the number 1 : ")
b =input("Enter the number 2 : ")

try:
    c= int(a) + int(b)
    print(c)
except Exception as e:
    print(e)
else:
    print("All inputs are good, Else clause got executed!!")

Enter the number 1 : 1
Enter the number 2 : 2
3
All inputs are good, Else clause got executed!!


## Try Finally keyword
Finally is a keyword which surely executes after the execution of the try except block of statement

In [105]:
a =input("Enter the number 1 : ")
b =input("Enter the number 2 : ")

try:
    c= int(a) + b
    print(c)
except:
    print("Error in try block")
finally:
    print("Finally runs post try except")

Enter the number 1 : 1
Enter the number 2 : 2
Error in try block
Finally runs post try except


In [106]:
a =input("Enter the number 1 : ")
b =input("Enter the number 2 : ")

try:
    c= int(a) + int(b)
    print(c)
except Exception as e:
    print(e)
else:
    print("All inputs are good, Else clause got executed!!")
finally:
    print("Finally runs post try except")

Enter the number 1 : 1
Enter the number 2 : 2
3
All inputs are good, Else clause got executed!!
Finally runs post try except


# Data Structures And Algorithms
- Arrays
- Stack
- Queue
- Linked List
- Linear Search
- Binary Search
- Insersion Sort
- Quick Sort
- Merge Sort

## Arrays:
- Linear Data structure 
- Continous Memory Locations
- Access elements randomly
- Homogeneous elements i.e. similar elements
### Applications
- Storing Information - linear fashion
- Suitable for applications that require frequent searching
### 1-Dimentional Array
- 1D can be related to a row
- Elements are stored one after another
- Only one subscript or index is used
### Declaration and Initialization 
- Array declaration:
    - Datatype varname [size]
- Can also do declaration and initialization at once:
    - Datatype varname [] = {ele1, ele2, ele3, ele4};
### 2-Dimentional Array
- 2D can be related to a table or matrix
- Elements are stored one after another i.e. one 1D array inside another.
- Two subscripts or indices are used, one row and one column.
- Dimensions depends upon the number of subscripts used.

In [108]:
# 1D array
print("How many elements to store inside the array", end="")
num = input()
arr = []
print("\nEnter", num, "Element:", end="")
num = int(num)
for i in range(num):
    element = input()
    arr.append(element)
print("\nThe array elements are")
for i in range(num):
    print(arr[i], end="")

How many elements to store inside the array3

Enter 3 Element:2
3
4

The array elements are
234

In [112]:
# 2D Array
r_num = int(input("Input number of rows: "))
c_num = int(input("Input number of columns: "))
twoD_arr = [[0 for col in range(c_num)] for row in range(r_num)]
# print("Enter the elements of the matrix: ")
# for i in range(r_num):
#     for j in range(c_num):
#         twoD_arr[i][j] = int(input())
print("The matrix is: ")
for i in range(r_num):
    for j in range(c_num):
        print(twoD_arr[i][j], i*j)
        twoD_arr[i][j]= i*j
print(twoD_arr)

Input number of rows: 2
Input number of columns: 3
The matrix is: 
0 0
0 0
0 0
0 0
0 1
0 2
[[0, 0, 0], [0, 1, 2]]


In [114]:
# Array with user defined value
print(end="Enter the size of Array: ")
tot = int(input())
arr = []
print(end="Enter " +str(tot)+ " Elements: ")
for i in range(tot):
    arr.append(input())
print(end="\nEnter the value to Delete: ")
val = input()
if val in arr:
    arr.remove(val)
    print("\nThe new array is: ")
    for i in range(tot-1):
        print(end=arr[i]+" ")
else:
    print("\nElement doent exist in the List!")

Enter the size of Array: 7
Enter 7 Elements: 1
2
3
4
5
6
7

Enter the value to Delete: 4

The new array is: 
1 2 3 5 6 7 

In [115]:
# Sort elements in an array
arr = [10, 22, 38, 27, 11]
temp = 0;

#Displaying elements of original array
print("Elements of original array: ");
for i in range(0, len(arr)):
    print(arr[i], end=" ");

#Sort the array in ascending order
for i in range(0, len(arr)):
    for j in range(i + 1, len(arr)):
        if(arr[i] > arr[j]):
            temp = arr[i];
            arr[i] = arr[j];
            arr[j] = temp;
print();
#Displaying elements of the array after sorting
print("\nElements of array sorted in ascending order: ")
for i in range(0, len(arr)):
    print(arr[i], end=" ");

Elements of original array: 
10 22 38 27 11 

Elements of array sorted in ascending order: 
10 11 22 27 38 

In [116]:
# Search element in an array
import array
arr = array.array('i', [1, 2, 3, 1, 2, 5])
print("Elements of original array: ")
for i in range(0, 6):
    print(arr[i], end=" ");
print("\r");
print("The index of first occurance of 2 is: ", end="")
print(arr.index(2))
print("The index of first occurance of 1 is: ", end="")
print(arr.index(1))

Elements of original array: 
1 2 3 1 2 5 
The index of first occurance of 2 is: 1
The index of first occurance of 1 is: 0


### Advantages of an array
- Random access elements
- Easy sorting and iteration
- Replacement of multiple variables
### Disadvantage of an array
- Size is fixed
- Difficult to insert and delete
- If capacity is more and occupancy less most of the array gets wasted
- Needs continous memory

## Stack
- Linear data structure
- It follows Last In First Out(LIFO) order
- Insertion and removal of the element has done at one end
- Push is used for inserting an element in a stack
- Pop is used to removal an element in a stack
### Functions
- push(x) - it is used to insert the element 'x' at the end of a stack.
- pop() - it is used to remove the topmost/last element of a stack.
- size() - gives the size/length of a stack.
- top() - give reference of last element present in stack
- empty() - return true for an empty stack
### Implementation of Stack
Several ways to implement stack in python
- list
- collections.deque
- queue.LifoQueue
### Implementation of stack using list
List in python can be used as stack
- append() - it is used to insert the element
- pop() - it is used to remove the last element

Logic- 

stack = []

stack.append("abc")

print(stack.pop())


In [117]:
# Implementation of stack using list
stack= []
stack.append("Welcome")
stack.append("to")
stack.append("great learning")
print(stack)
print(stack.pop())
print(stack)

['Welcome', 'to', 'great learning']
great learning
['Welcome', 'to']


### Implementation of stack using deque
- STACK in python are created by the collection module which provides deque class.
- Append and pop operations are faster in deque as compared to list

Logic:

from collectios import deque

stack = deque()

stack.append("abc")

print(stack.pop())

In [119]:
### Implementation of stack using deque
from collections import deque
stack = deque()
stack.append("Welcome")
stack.append("to")
stack.append("great learning")
print(stack)
print(stack.pop())
print(stack)

deque(['Welcome', 'to', 'great learning'])
great learning
deque(['Welcome', 'to'])


### Implementation of stack using queue
- Queue module contains the LIFO queue
- It is having some additional functions and works same as stack
- Put function is used to insert the data in queue
- Get function is used to remove the element
### Functions available in queue model
- get() - it is used to remove the element from queue
- maxsize() - Used to put the maximum number of items allowed in queue
- empty() - It return true when queue is empty else false
- full() - When queue is full returns True
- put(x) - It is used to insert x in queue
- qsize() - Gives size of a queue

Logic: 

from queue import LifoQueue

stack = Lifoqueue()


In [122]:
# Implementation of stack using queue
from queue import LifoQueue
stack = LifoQueue(maxsize=3)
stack.put("Welcome")
stack.put("to")
stack.put("great learning")
print(stack)
print(stack.qsize())
print(stack.full())
print(stack.get())
print(stack.qsize())
print(stack)

3
True
great learning
2


## What is Queue
- Linear data structure
- Follows FIFO: First in first out
- Insertion can take place from the rear end
- Deletion can take place from front end
- Queue at ticket counter, bus station
- 4 major operations
    - enqueue(ele) - used to insert element at top
    - dequeue() - removes the top element from queue
    - peekfirst() - to get first element of queue
    - peeklast() - to get last element of queue
- All operation works in constant time i.e. 0(1)

### Applications of Queue
- Scheduling
- Maintaining playlist
- Interrupt handling
## Queue Implementation
- Enqueue
- Dequeue
- Display

In [123]:
# Implementation of stack using queue
class Queue:
    def __init__(self):
        self.queue = []
    def enqueue(self, data):
        self.queue.append(data)
    def dequeue(self):
        if len(self.queue)<1:
            return None
        return self.queue.pop(0)
    def display(self):
        print(self.queue)
    def size(self):
        return len(self.queue)

In [124]:
q = Queue()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
q.enqueue(4)
q.display()
q.dequeue()
q.display()

[1, 2, 3, 4]
[2, 3, 4]


### Queue Implementation
A program implementation for circular queue:
- Enqueue
- Dequeue

In [126]:
# circular queue 
class MyCircularQueue():
    def __init__(self, k):
        self.k = k
        self.queue = [None] * k
        self.head = self.tail = -1

    def enqueue (self, data):
        if((self.tail + 1) % self.k == self.head):
            print("Queue is full")
        elif (self.head == -1):
            self.head = 0
            self.tail = 0
            self.queue[self.tail] = data
        else:
            self.tail = (self.tail + 1) % self.k
            self.queue[self.tail] = data
            
    def dequeue(self):
        if(self.head == -1):
            print("Queue is empty")
        elif(self.head == self.tail):
            temp = self.queue[self.head]
            self.head = -1
            self.tail = -1
            return temp
        else:
            temp = self.queue[self.head]
            self.head = (self.head + 1) % self.k
            return temp
        
    def printCQueue(self):
        if(self.head == -1):
            print("No element in circular queue is found")
        elif(self.tail >= self.head):
            for i in range(self.head, self.tail + 1):
                print(self.queue[i], end = " ")
            print()
        else:
            for i in range(self.head, self.k):
                print(self.queue[i], end = " ")
            for i in range(0, self.tail + 1):
                print(self.queue[i], end = " ")
            print()

In [127]:
obj = MyCircularQueue(5)
obj.enqueue(12)
obj.enqueue(22)
obj.enqueue(31)
obj.enqueue(44)
obj.enqueue(57)
print("Initial queue values")
obj.printCQueue()

obj.dequeue()
print("After removing an element from the queue")
obj.printCQueue()

Initial queue values
12 22 31 44 57 
After removing an element from the queue
22 31 44 57 


### Advantages of queue
- Maintains data in FIFO manner
- Insersion from beginning and deletion from end takes O(1) time
### Disadvantages of queue
- Manipulation is restricted front and rear
- Not much flexible

## Linked List
It is collection or group of nodes

Each node contains data and reference (pointer) which contains the address of next node.

It is linear data structure

Elements are stored randomly in memory

### Why Linked List
- Linked list is having more efficiency for performing the operations as compared to list
- Elements are stored randomly whereas in list at continuous memory
- Accessing the elements in linked list will be slower as compared to list
- Utilization of memory is higher than the list

### Singly Linked List
- It is trversed only in one direction

### Operations of Singly Linked List
- Insertion
- Deletion
- Traversal


### Pseudo Code
Creating a node in Singly Linked List

Class Node:

    def __init__(self, data):

        self.data=data;

        self.reference=None;
    
node1= Node(7)

print(node1.data)

print(node1.reference)



Creating a clas of singly Linked list

class LinkedList

    def __init__(self):

        self.head=None;

In [ ]:
# Creating a node class
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
n1 = Node(7)
print(n1.data)
print(n1.next)


In [129]:
# creation of Singly Linked List
class SinglyLinkedList:
    def __init__(self):
        self.head = None

sll = SinglyLinkedList()
print(sll.head) 

None


## Searching Algorithms
### Linear Search Algorithm

What is Linear Search
- It helps you to search for an element in a linear data structure.
- It checks each and every element for the element to be searched.
- Since this is done in linear fashion, it is termed as linear search.

In [130]:
# linearSearch(arr, item)
#     for each element in array
#         if element == item
#             return index
#     return -1

def linearSearch(arr, n, x):
    for i in range(0, n):
        if (array[i] == x):
            return i
    return -1

array =[2, 4, 0, 1, 9]
n = len(array)
x = 1
result = linearSearch(array, n, x)
if(result == -1):
    print("Element not found")
else:
    print("Element found at index: ", result)

Element found at index:  3


## Linear search - Time complexity
- Best Time complexity: O(1)
- Average Time complexity: O(n)
- Worst Time complexity: O(n)
- Here all the elements need to be compared in worst case to search for a given element.
- Best case could be the case where the first element matched to the element to be searched
## Linear search - Space complexity
- No auxiliary space is required in linear search implementation.
- Hence space complexity is : O(1)

## What is Binary Search
- Binary search is one of the searching technique
- It is used to search an element in a sorted array
- This searching technique is based on divide and conquer strategy and search space always reduces to half in every iteration
- This is very efficient technique for searching but it needs some order on which partition of the array will occur


In [ ]:
## Binary Search - Iterative Algorithm
# binarySearch(arr, size)
#     loop until beg is not equal to end 
#         midindex = (beg + end) / 2
#         if arr[midindex] == item
#             return midindex
#         else if item > arr[midindex]
#             beg = midindex + 1
#         else
#             end = midindex - 1

In [ ]:
## Binary Search - Recursive Algorithm
# binarysearch(arr, beg, end, item)
#     if beg <= end
#         mid = (beg + end) / 2
#         if arr[mid] == item
#             return mid
#         else if item > arr[mid]
#             return binarysearch(arr, mid + 1, end, item)
#         else
#             return binarysearch(arr, beg, mid - 1, item)
#     else
#         return -1

In [138]:
# Binary search in Python
def binarySearch(arr, l, r, x):
    while l <= r:
        mid = l + (r - l) // 2
        if arr[mid] == x:
            return mid
        elif arr[mid] < x:
            l = mid + 1
        else:
            r = mid - 1
    return -1   
   

In [139]:
array = [3,4,5,6,7,8,9]
x = 4
result = binarySearch(array, 0, len(array)-1, x)
if(result == -1):
    print("Element not found")
else:
    print("Element found at index: ", result)

Element found at index:  1


## Binary Search - Time Complexity O(log n)
- Best time complexity: O(1)
- Average time complexity: O(log n)
- Worst time complexity: O(log n)
- In each iteration, the search space is getting divided by 2. That means that in the current iteration you have to deal with half of the previous iteration array. And above steps continue till beg<end.
- Best case could be the case where the first mid-value get matched to the element to be searched.
- Worst case could be the case where the last mid-value get matched to the element to be searched.

## Binary Search - Space Complexity O(1)
- No auxiliary space is required in binary search implementation.
- Hence space complexity is O(1).


## What is insertion sort
- It is one of the easiest and brute force sorting algorithms
- Insertion sort is used to sort elements in either ascending or descending order
- In insersion sort, we maintain a sorted part and unsorted part
- It works just like playing cards i.e. picking one card and sorting it with the cards that we have in our hand already which in turn are sorted
- With every iteration, one item from unsorted is moved to the sorted part
- First element is picked and considered  as sorted
- Then we start picking from 2nd elements onwards and start comparing it with elements in sorted part.
- We shift the elements from sorted by one element until an appropriate location is not found for the picked element
- This continues till all the elements get exhausted.


In [140]:
# Insertion sort using Python
def insersion_sort(array):
    for step in range(1, len(array)):
        key = array[step]
        j = step - 1
        while j >= 0 and key < array[j]:
            array[j + 1] = array[j]
            j = j - 1
        array[j + 1] = key
    return array

In [142]:
data = [5,2,1,7,8]
insersion_sort(data)
print(f"Sorted data: {data}")

Sorted data: [1, 2, 5, 7, 8]


### Insertion sort - Time Complexity
- In the worst case, it will take n to pick all elements and then at max n shifts to set it to the right position
- In best case that is sorted array we will just poick the elements but no shifting will take place leading it to n time complexity that is every element is traversed at least once
- Best Time complexity: O(n)
- Average Time complexity: O(n^2)
- Worst Time complexity: O(n^2)

### Insertion sort - Space Complexity
- No auxilary space is required in insertion sort implementation that is we are not using any arrays, linked list, stack, queue etc to store our elements
- Space Complexity: O(1)

### Insertion sort - Analysis
- Number of comparisons: O(n^2)
- Number of Swaps
- Stable or Unstable
- Inplace or Outplace

## Quick sort
- It is one of the most widely used sorting algorithm
- It follows divide and conquer algorithm
- Recursion is used in quicksort implementation
- In each recursive call, a pivot is chosen then the array is partitioned in such a way that all the elements less than pivot lie to the left and all the elements greater than pivot lie to the right
- After every call the chosen pivot occupies its correct position in the array which is supposed to be in sorted order
- So with each step, our problem gets reduced by 2 which leads to quick sorting
- Pivot can be last element of current array, first element of current array or any random element


In [ ]:
## Quick sort using python
def partition(array, low, high):
    pivot = array[high]
    i = low - 1
    for j in range(low, high):
        if array[j] <= pivot:
            i = i + 1
            (array[i], array[j]) = (array[j], array[i])
    (array[i + 1], array[high]) = (array[high], array[i + 1])
    return i + 1

## Quick sort function
def quick_sort(array, low, high):
    if low < high:
        pi = partition(array, low, high)
        quick_sort(array, low, pi - 1)
        quick_sort(array, pi + 1, high)
    return array

In [ ]:
d = [9,8,7,2,10,20,1]
print("Unsorted data: ", d)
size = len(d)
d = quick_sort(d, 0, size - 1)
print("Sorted data: ", d)

### Quick Sort - Time Complexity
- Best Case: O(nlogn)
- Average Case: O(nlogn)
- Worst Case: O(n^2)    
- Partition of elements take n time and in quicksort problem is divide by the factor 2

### Quick Sort - Space Complexity
- O(n): basic approach
- O(logn): modified approach

### Quick Sort - Stability
- It is unstable algorithm
### Quick Sort - In Place
- Yes   

## What is Merge Sort
- In merge sort problem is divided into two sub problmes in every iteration.
- Hence efficiency is increased drastically
- I follows divide and conquer approach
- Divide break the problem in two sub problems which continues until problem set is left with one element only
- Conquer basically merges the 2 sorted array into the original array


In [ ]:
### Merge sort -Algorithm
# mergseSort(arr, left, right)
#     if left>= right
#         return
#     mid = (left + right) / 2
#     mergeSort(arr, left, mid)
#     mergeSort(arr, mid + 1, right)
#     merge(arr, left, mid, right)
# end

### Merge - Algorithm
-  Create 2 subarrays left and right
- Create 3 iterators i, j, k    
- Insert elements in lft and right (i& j)
- k - Replace the values in the original array
- Pick the larger elements from left and right and place them in the correct position
- If there are no elements in either left or right, pick up the remaining elements either from left or right and insert in original array


In [146]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_arr = arr[:mid]
        right_arr = arr[mid:]

        # Recursive call on each half
        merge_sort(left_arr)
        merge_sort(right_arr)

        # Two iterators for traversing the two halves
        i = j = k = 0

        # Compare elements of left and right halves
        while i < len(left_arr) and j < len(right_arr):
            if left_arr[i] < right_arr[j]:
                arr[k] = left_arr[i]
                i += 1
            else:
                arr[k] = right_arr[j]
                j += 1
            k += 1

        # Checking if any element was left
        while i < len(left_arr):
            arr[k] = left_arr[i]
            i += 1
            k += 1

        while j < len(right_arr):
            arr[k] = right_arr[j]
            j += 1
            k += 1  
            
def printList(arr):
    for i in range(len(arr)):
        print(arr[i], end=" ")
    print()


In [147]:
if __name__ == '__main__':
    arr = [11,34,2,18,33,22,88,9]
    merge_sort(arr)
    print("Sorted array is: ", arr)

Sorted array is:  [2, 9, 11, 18, 22, 33, 34, 88]


# Python For Machine Learning
- Numpy
- Pandas
- Matplot Lib
- Seaborn

### Numpy
- Numpy stands for Numerical python and is the core library for numeric and scientific computing
- It consists of multi-dimensional array objects and a collection of routines for processing those arrays

In [149]:
import numpy as np

arr = np.array([10, 22, 38, 27, 11])
arr

array([10, 22, 38, 27, 11])

In [152]:
type(arr)

numpy.ndarray

In [159]:
# Multi-dimensional
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
# Numpy array with zeros
n2 = np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [161]:
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [197]:
# Numpy with onces
n3= np.ones((3,2))
n3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [162]:
# Numpy array with same number
n4 = np.full((2,2),10)
n4

array([[10, 10],
       [10, 10]])

In [163]:
# Numpy array within a range
n5 = np.arange(11, 21)
n5

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [165]:
n6 = np.arange(10,50,5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45])

In [167]:
n7 = np.arange(50,10,-5)
n7

array([50, 45, 40, 35, 30, 25, 20, 15])

In [183]:
# Numpy with random numbers
n8 = np.random.randint(1, 100, 5)
n8

array([15,  5, 69, 63, 61])

In [185]:
# Numpy with random numbers
n9 = np.random.randint(-100, -1, 5)
n9

array([-81, -45, -32, -90, -56])

In [187]:
# Numpy shape
n10 = np.array([[1, 2, 3], [4, 5, 6]])
n10.shape

(2, 3)

In [190]:
# Numpy shape change
n10.shape = (3,2)
n10

array([[1, 2],
       [3, 4],
       [5, 6]])

In [191]:
# vstack()
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.vstack((n1, n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
# vstack()
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
n3 = np.array([1, 2, 3])
np.vstack((n1, n2, n3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [193]:
# hstack()
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.hstack((n1, n2))

array([1, 2, 3, 4, 5, 6])

In [199]:
# hstack()
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
n3 = np.array([4])
np.hstack((n1, n2, n3))

array([1, 2, 3, 4, 5, 6, 4])

In [195]:
# column_stack()
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.column_stack((n1, n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [204]:
# Numpy intersection
n1 = np.arange(10, 61, 10)
n2 = np.arange(50, 91, 10)
np.intersect1d(n1, n2)

array([50, 60])

In [205]:
# Numpy unique in one array with respect to other array
n1 = np.arange(10, 61, 10)
n2 = np.arange(50, 91, 10)
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [206]:
# Numpy unique in one array with respect to other array
n1 = np.arange(10, 61, 10)
n2 = np.arange(50, 91, 10)
np.setdiff1d(n2, n1)

array([70, 80, 90])

In [221]:
# Numpy Array Mathematics: total addition of all numbers
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
n3 = np.sum([n1, n2])
n3

np.int64(21)

In [208]:
# Numpy Array Mathematics: addition of all columns
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.sum([n1, n2], axis =0)

array([5, 7, 9])

In [209]:
# Numpy Array Mathematics: addition of all rows
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.sum([n1, n2], axis =1)

array([ 6, 15])

In [210]:
# Numpy scaler Operations
# Addition
n1 = np.array([1, 2, 3])
n1+1

array([2, 3, 4])

In [211]:
# Subtraction
n1 = np.array([1, 2, 3])
n1-1

array([0, 1, 2])

In [213]:
# Multiplication
n1 = np.array([1, 2, 3])
print(n1 * 2)
print(n1)

[2 4 6]
[1 2 3]


In [214]:
# Division
n1 = np.array([1, 2, 3])
n1/2

array([0.5, 1. , 1.5])

In [220]:
# Mathematical functions
n1 = np.array([10,22,37,41,59,63,74,85])
print(f"Mean is : {np.mean(n1)}")
print(f"median is : {np.median(n1)}")
print(f"Standard deviation is : {np.std(n1)}")

Mean is : 48.875
median is : 50.0
Standard deviation is : 24.17352632530058


In [223]:
# Numpy Matrix
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [224]:
# rows
print(n1[0])
print(n1[1])
print(n1[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [225]:
# columns
print(n1[:, 0])
print(n1[:, 1])
print(n1[:, 2])

[1 4 7]
[2 5 8]
[3 6 9]


In [229]:
# Matrix Transpose: Interchanging rows and columns
print(f"Original matrix is {n1}")
print(f"Transposed matrix is {n1.transpose()}")

Original matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix is [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [231]:
# Matrix Multiplication:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n2 = np.array([[9,7,8], [6,5,4], [3,2,1]])
n3 = np.dot(n1, n2)
n4 = np.dot(n2, n1)
print(f"np.dot(n1, n2) : {n3}")
print(f"np.dot(n2, n1) : {n3}")
n5 = n1.dot(n2)
n6 = n2.dot(n1)
print(f"n1.dot(n2) : {n5}")
print(f"n2.dot(n1) : {n6}")

np.dot(n1, n2) : [[ 30  23  19]
 [ 84  65  58]
 [138 107  97]]
np.dot(n2, n1) : [[ 30  23  19]
 [ 84  65  58]
 [138 107  97]]
n1.dot(n2) : [[ 30  23  19]
 [ 84  65  58]
 [138 107  97]]
n2.dot(n1) : [[ 93 117 141]
 [ 54  69  84]
 [ 18  24  30]]


In [232]:
# Saving and loading numpy array
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.save('test.npy', n1)
n2 = np.load('test.npy')
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])